[changelog]
header = """
# Changelog

"""
body = """
{% if version %}## {{ version }} ({{ timestamp | date(format=\"%Y-%m-%d\") }}){% else %}## Unreleased{% endif %}
{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }} ({{ commit.id | truncate(length=7, end=\"\") }})
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '^chore\\(release\\):', replace = '' }
]
commit_parsers = [
  { message = '^feat', group = 'Features' },
  { message = '^fix', group = 'Bug Fixes' },
  { message = '^perf', group = 'Performance' },
  { message = '^refactor', group = 'Refactoring' },
  { message = '^docs', group = 'Documentation' },
  { message = '^test', group = 'Tests' },
  { message = '^build', group = 'Build' },
  { message = '^ci', group = 'CI' },
  { message = '^chore', group = 'Chores' },
  { message = '^revert', group = 'Reverts' }
]
protect_breaking_commits = true
filter_commits = false
sort_commits = "oldest"
tag_pattern = "v[0-9]*"