[app]
user = "YOUR_USER"
passwd = "YOUR_PASSWORD"
mac = "YOUR_MAC"
imei = ""
address = ""
interface = "YOUR_INTERFACE"
bind = "[::]:7088"
rtsp_proxy = true
udp_proxy = true

[auth]
token = "YOUR_TOKEN"
protect = ["playlist", "xmltv", "manage"]

[manage]
enabled = true

[alias]
mode = "first_match"

[[alias.rules]]
type = "regex"
pattern = "(?i)^CCTV\\s*[-\\s]*\\s*4K.*$"
replace = "CCTV4K"

[[alias.rules]]
type = "regex"
pattern = "(?i)^CCTV\\s*[-\\s]*\\s*4.*$"
replace = "CCTV4"

[[alias.rules]]
type = "regex"
pattern = "(?i)^CCTV[-\\s]*(\\d{1,2}(\\s*P(LUS)?|[K\\+])?).*"
replace = "CCTV$1"

[[alias.rules]]
type = "regex"
pattern = "^广东\\s*4K.*$"
replace = "广东4K"

[[alias.rules]]
type = "regex"
pattern = "^CGTN.*$"
replace = "CGTN"

[[alias.rules]]
type = "regex"
pattern = "^广东卫视\\s*4k.*$"
replace = "广东卫视"

[[alias.rules]]
type = "regex"
pattern = "(?i)^(.+?)(?:[-\\s]|高清|超清|超高清|4K|[25]0P|时移|专用|测试)*$"
replace = "$1"

[resolution]
default_score = 0

[[resolution.rules]]
pattern = "(?i)4k|2160p|ultra\\s*hd|uhd"
score = 400
label = "R4K"

[[resolution.rules]]
pattern = "(?i)超高清"
score = 350
label = "Uhd"

[[resolution.rules]]
pattern = "(?i)超清|1080p|fhd"
score = 300
label = "Fhd"

[[resolution.rules]]
pattern = "(?i)高清|720p|hd"
score = 200
label = "Hd"

[[resolution.rules]]
pattern = "(?i)标清|sd|576p|480p"
score = 100
label = "Sd"

[groups]
default_group = "未分组"

[[groups.entries]]
group = "#IPTV-央视"
channels = ["CCTV1", "CCTV2", "CCTV3", "CCTV4", "CCTV5", "CCTV5+", "CCTV6", "CCTV7", "CCTV8", "CCTV9", "CCTV10", "CCTV11", "CCTV12", "CCTV13", "CCTV14", "CCTV15", "CCTV16", "CCTV17", "CCTV4K", "CGTN", "CGTN Documentary", "CGTN西班牙语", "CGTN法语", "CGTN阿拉伯语", "CGTN俄语"]

[[groups.entries]]
group = "#IPTV-卫视"
channels = ["湖南卫视", "浙江卫视", "江苏卫视", "东方卫视", "安徽卫视", "广东卫视", "北京卫视", "天津卫视", "山东卫视", "江西卫视", "湖北卫视", "厦门卫视", "辽宁卫视", "黑龙江卫视", "吉林延边卫视", "山西卫视", "贵州卫视", "四川卫视", "河南卫视", "云南卫视", "重庆卫视", "河北卫视", "东南卫视", "广西卫视", "吉林卫视", "青海卫视", "海南卫视", "宁夏卫视", "内蒙古卫视", "西藏卫视", "新疆卫视", "甘肃卫视", "兵团卫视", "三沙卫视", "陕西卫视"]

[[groups.entries]]
group = "#IPTV-广东电视台"
channels = ["广东卫视", "广东4K", "广东珠江", "广东新闻", "广东民生", "广东移动", "广东体育", "经济科教", "大湾区卫视", "广东影视", "广东少儿", "嘉佳卡通", "南方购物", "岭南戏曲", "现代教育"]

[[groups.entries]]
group = "#IPTV-广州电视台"
channels = ["广州综合", "广州新闻", "广州法治"]

[[groups.entries]]
group = "#IPTV-深圳电视台"
channels = ["深圳卫视", "深圳都市", "深圳电视剧频道", "深圳财经生活", "深圳体育健康", "深圳少儿频道", "深圳宝安频道", "深圳龙岗频道", "深圳宜和购物"]

[[groups.entries]]
group = "#IPTV-广东地方台"
channels = ["韶关新闻综合", "湛江新闻综合", "湛江公共", "揭阳综合", "揭阳生活", "汕尾新闻综合", "汕尾文化生活", "江门综合", "HZTV-1", "HZTV-2", "珠海-1", "肇庆综合", "肇庆生活服务", "河源综合", "河源公共", "清远新闻综合", "云浮综合", "云浮文旅", "茂名综合", "茂名公共", "汕头综合", "汕头经济生活", "佛山公共", "佛山南海", "佛山顺德", "佛山综合", "东莞新闻综合", "东莞生活资讯", "中山综合", "香山文化", "潮州综合", "潮州民生", "梅州综合", "客家生活", "阳江-1", "阳江-2"]

[[groups.entries]]
group = "#IPTV-央视网台"
channels = ["电视指南", "兵器科技", "风云足球", "央视台球", "高尔夫网球", "女性时尚", "世界地理", "怀旧剧场", "风云剧场", "央视文化精品", "第一剧场", "风云音乐", "优漫卡通", "卡酷动画", "卫生健康", "经典电影", "老故事", "魅力时尚", "CGTN英文记录", "CGTN英语"]

[[groups.entries]]
group = "#IPTV-数字付费"
channels = ["金鹰卡通", "CETV-1", "中国教育-1", "CETV-4","爱体育", "汽摩", "热播剧场", "爱大剧", "爱电影", "爱综艺", "早期教育", "中国天气", "茶", "国学", "央视精品", "少儿动画", "快乐垂钓", "金鹰纪实", "求索纪录", "天元围棋", "睛彩"]

[[groups.entries]]
group = "#IPTV-IPTV频道"
channels = ["IPTV1", "IPTV2", "IPTV3", "PPTV-1", "PPTV-2", "PPTV-3", "PPTV-4", "CETV2", "CETV4", "IPTV爱综艺", "IPTV爱体育", "IPTV爱电影", "IPTV爱大剧", "IPTV谍战剧场", "IPTV相声小品", "IPTV野外", "IPTV法治", "IPTV魅力时尚", "IPTV经典电影", "IPTV热播剧场", "IPTV少儿动画"]

[[groups.entries]]
group = "#IPTV-百视通"
channels = ["百视通体育直播室1","百视通体育直播室4","百视通体育直播室5","百视通体育直播室6","百视通体育直播室7" ]


[sorting]
same_alias = ["resolution_desc", "prefer_resolution", "original"]

[sorting.prefer_resolution]
order = ["R4K", "Uhd", "Fhd", "Hd", "Sd", "Unknown"]

[template]
extinf = '#EXTINF:-1 tvg-id="{{tvg_id}}" tvg-name="{{alias_name}}" tvg-chno="{{tvg_chno}}"{{catchup_attr}}tvg-logo="{{tvg_logo}}" group-title="{{group}}",{{alias_name}}'
url = '{{url}}'

[xmltv]
use_alias_name = true
